<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic_integration.pipedrive.guzzle.client' shared service.

return $this->services['mautic_integration.pipedrive.guzzle.client'] = new \GuzzleHttp\Client();
