<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.helper.export' shared service.

return $this->services['mautic.helper.export'] = new \Mautic\CoreBundle\Helper\ExportHelper(($this->services['translator.default'] ?? $this->getTranslator_DefaultService()));
