<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.core.command.transifex_pull' shared service.

return $this->services['mautic.core.command.transifex_pull'] = new \Mautic\CoreBundle\Command\PullTransifexCommand(($this->services['transifex.factory'] ?? $this->load('getTransifex_FactoryService.php')), ($this->services['translator.default'] ?? $this->getTranslator_DefaultService()), ($this->services['mautic.helper.core_parameters'] ?? ($this->services['mautic.helper.core_parameters'] = new \Mautic\CoreBundle\Helper\CoreParametersHelper($this))));
