<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOUaEqDg\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOUaEqDg/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerOUaEqDg.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerOUaEqDg\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerOUaEqDg\appAppKernelProdContainer([
    'container.build_hash' => 'OUaEqDg',
    'container.build_id' => '658ebd18',
    'container.build_time' => 1658840632,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOUaEqDg');
